### ISSUE TITLE
Enforce that message handlers are well-defined with static_asserts

### ISSUE THREAD

**Issue by Viech** [Unvanquished/Unvanquished-CBSE#10]
In case there is a way to make message handlers virtual functions inside the component base class without sacrificing performance on every message call, do so, as it will produce nicer error messages when a handler is omitted or badly defined. Otherwise #1 needs to be sufficient.

**Comment by Kangz** [comment]
I remember talking to Amanieu about this and there is no way to make sure the handler prototype is correct, up to cast in the arguments (I think). Not sure what to do about this.

**Comment by Kangz** [comment]
Closing as not fixable.
