### ISSUE TITLE
Allow entity constructor to pass values to component constructors

### ISSUE THREAD

**Issue by Viech** [Unvanquished/Unvanquished-CBSE#14]
When a component constructor takes parameters and they are (partly) not supplied inside the entity definitions that use that component, the entity in question should make them parameters of the entity constructor and pass them to the relevant components.

This is important in order to be able to read entity configuration from config files during runtime, without adding messages that are solely used for configuration. For example, instead of setting the maximum health of AcidTubeBuildable inside the HealthComponent declaration inside the entity definition, the constructor of the AcidTubeBuildable would take the maximum health as a parameter, read from a configuration file during runtime. (I have to admit, this specific example doesn't really show the importance of the feature but it should make clear what I mean in general.)

To prevent name clashes, the component name can be prepended, though it would be nice if this only happens on actual clashes.

A more advanced solution that allows detailed configuration to be passed to an entity is to provide every entity with a configuration dictionary as the only extra argument of the constructor. That dictionary would then be queried for all missing (component) initialization parameters. If a configuration is not found, a default paramter (which needs to be added to every component parameter inside the component definition) would be used instead. This allows for a very flexible configuration hierarchy: Component defaults < entity defaults < runtime configuration. The dictionary itself could also contain a hierarchy (in the form of `dictionary[component][key]`) that is reflected by the runtime configuration files to prevent any name clashes.

**Comment by Kangz** [comment]
Resolved, see https://gist.github.com/Kangz/3f77987f9d1ec0083a14

**Comment by Kangz** [comment]
Implemented in c6cefc4e8ad39aab9f2936044ab8a5ce9504a024 and 5a9b89e05ae5906f414b6beaec78799e39891c95
