### ISSUE TITLE
Add license statements to templates and generator

### ISSUE THREAD

**Issue by Viech** [Unvanquished/Unvanquished-CBSE#16]
Both the generator and the templates as such need a copyright/license statement before we can add them to the main repository. The latter shouldn't show up on the autogenerated content by using jinja's internal comments.

I propose to add them to "Daemon BSD Source Code".

**Comment by Kangz** [comment]
I think the LICENSE file is enough. Closing.

**Comment by Viech** [comment]
I think it's not, I'm talking about what needs to happen so that we can put these in the main repository, where every source file has such a header.
