### ISSUE TITLE
Don't require manual modificatios to CmakeList.txt when adding components

### ISSUE THREAD

**Issue by Viech** [Unvanquished/Unvanquished-CBSE#6]
Find a way to automatically add the component implementation files to the build process, e.g. by generating a file that is somehow included by cmake. After all, we want to encourage people to make good use of dedicated components instead of overloading existing ones out of lazyness to edit `CmakeList.txt`. :wink:

**Comment by Kangz** [comment]
@DolceTriade would a glob on src/gamelogic/sgame/Component*.cpp be ok for you though? Otherwise we will need to make some file the CMakeLists.txt includes, which is ugly.

**Comment by DolceTriade** [comment]
ya go for it. Autogenerated files shouldn't be incomplete/not compile.

**Comment by Kangz** [comment]
Ok closing the issue since we decided on that topic.
